name       : libssh
version    : 0.8.4
release    : 5
source     :
    - https://www.libssh.org/files/0.8/libssh-0.8.4.tar.xz : 6bb07713021a8586ba2120b2c36c468dc9ac8096d043f9b1726639aa4275b81b
license    : LGPL-2.1-or-later
component  : programming
summary    : SSH library
description: |
    libssh is a multi-platform C library implementing the SSHv2 and SSHv1 protocol on client and server side. With libssh, you can remotely execute programs, transfer files, use a secure and transparent tunnel, manage public keys and much more.
builddeps  :
    - pkgconfig(cmocka)     # check
setup      : |
    mkdir build && cd build
    %cmake -DUNIT_TESTING=ON ..
build      : |
    %make -C build
install    : |
    %make_install -C build
check      : |
    # torture_misc fails in the sandbox but should work when executed manually
    %make test -C build || :
