name       : libssh
version    : 0.7.3
release    : 2
source     :
    - https://red.libssh.org/attachments/download/195/libssh-0.7.3.tar.xz : 26ef46be555da21112c01e4b9f5e3abba9194485c8822ab55ba3d6496222af98
license    : LGPL-2.0
component  : programming
summary    : SSH library
description: |
    libssh is a multi-platform C library implementing the SSHv2 and SSHv1 protocol on client and server side. With libssh, you can remotely execute programs, transfer files, use a secure and transparent tunnel, manage public keys and much more.
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
