name       : libssh
version    : 0.7.1
release    : 1
source     :
    - https://red.libssh.org/attachments/download/154/libssh-0.7.1.tar.xz : 2fc7ccf96d3263cbd8ab520118cb94d9a2e11714c61e22b3f761fc5352fd046d
license    : LGPL-2.0+
summary    : SSH library
description: |
    libssh is a mulitplatform C library implementing the SSHv2 and SSHv1 protocol on client and server side. With libssh, you can remotely execute programs, transfer files, use a secure and transparent tunnel, manage public keys and much more.
builddeps  :
clang      : no
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
