name       : libssh
version    : 0.9.2
release    : 8
source     :
    - https://www.libssh.org/files/0.9/libssh-0.9.2.tar.xz : 1970a8991374fc8cbdcb7fcc3683fe8f8824aa37d575f38cfb75fe0fe50fd9ad
license    : LGPL-2.1-or-later
component  : programming
summary    : SSH library
description: |
    libssh is a multi-platform C library implementing the SSHv2 and SSHv1 protocol on client and server side. With libssh, you can remotely execute programs, transfer files, use a secure and transparent tunnel, manage public keys and much more.
builddeps  :
    - pkgconfig(cmocka)     # check
setup      : |
    %cmake_ninja -DUNIT_TESTING=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    # torture_misc fails in the sandbox but should work when executed manually
    %ninja_check || :
