name       : libssh
version    : 0.7.5
release    : 3
source     :
    - https://red.libssh.org/attachments/download/218/libssh-0.7.5.tar.xz : 54e86dd5dc20e5367e58f3caab337ce37675f863f80df85b6b1614966a337095
license    : LGPL-2.0
component  : programming
summary    : SSH library
description: |
    libssh is a multi-platform C library implementing the SSHv2 and SSHv1 protocol on client and server side. With libssh, you can remotely execute programs, transfer files, use a secure and transparent tunnel, manage public keys and much more.
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
