name       : libssh
version    : 0.8.6
release    : 6
source     :
    - https://www.libssh.org/files/0.8/libssh-0.8.6.tar.xz : 1046b95632a07fc00b1ea70ee683072d0c8a23f544f4535440b727812002fd01
license    : LGPL-2.1-or-later
component  : programming
summary    : SSH library
description: |
    libssh is a multi-platform C library implementing the SSHv2 and SSHv1 protocol on client and server side. With libssh, you can remotely execute programs, transfer files, use a secure and transparent tunnel, manage public keys and much more.
builddeps  :
    - pkgconfig(cmocka)     # check
setup      : |
    mkdir build && cd build
    %cmake -DUNIT_TESTING=ON ..
build      : |
    %make -C build
install    : |
    %make_install -C build
check      : |
    # torture_misc fails in the sandbox but should work when executed manually
    %make test -C build || :
