name       : libssh
version    : 0.10.5
release    : 14
source     :
    - https://www.libssh.org/files/0.10/libssh-0.10.5.tar.xz : b60e2ff7f367b9eee2b5634d3a63303ddfede0e6a18dfca88c44a8770e7e4234
license    : LGPL-2.1-or-later
component  : programming.library
summary    : SSH library
description: |
    libssh is a multi-platform C library implementing the SSHv2 and SSHv1 protocol on client and server side. With libssh, you can remotely execute programs, transfer files, use a secure and transparent tunnel, manage public keys and much more.
builddeps  :
    - pkgconfig(cmocka)     # check
setup      : |
    %cmake_ninja -DUNIT_TESTING=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    # torture_misc fails in the sandbox but should work when executed manually
    %ninja_check || :
