name       : libssh
version    : 0.8.1
release    : 4
source     :
    - https://git.libssh.org/projects/libssh.git/snapshot/libssh-0.8.1.tar.gz : dcc6cd959b029ebb12a090229ae96763f252267da3adeeaa83b3bcc30a79690d
license    : LGPL-2.0
component  : programming
summary    : SSH library
description: |
    libssh is a multi-platform C library implementing the SSHv2 and SSHv1 protocol on client and server side. With libssh, you can remotely execute programs, transfer files, use a secure and transparent tunnel, manage public keys and much more.
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
