name       : libssh
version    : 0.9.1
release    : 7
source     :
    - https://www.libssh.org/files/0.9/libssh-0.9.1.tar.xz : 33249bb616bb696e184cf930ea5d14239b65bb999c0815589efc35e5ed895787
license    : LGPL-2.1-or-later
component  : programming
summary    : SSH library
description: |
    libssh is a multi-platform C library implementing the SSHv2 and SSHv1 protocol on client and server side. With libssh, you can remotely execute programs, transfer files, use a secure and transparent tunnel, manage public keys and much more.
builddeps  :
    - pkgconfig(cmocka)     # check
setup      : |
   %cmake_ninja -DUNIT_TESTING=ON ..
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    # torture_misc fails in the sandbox but should work when executed manually
    %make test -C build || :
